define([], function () {
  return {
    PropertyPaneDescription: 'Configure Navigation Tabs to display links from a SharePoint list organized by categories.',
    DataGroupName: 'Data Source',
    LayoutGroupName: 'Layout & Display',
    ListFieldLabel: 'Select a list',
    LayoutTypeFieldLabel: 'Layout type',
    CardsPerRowFieldLabel: 'Items per row',
    ShowDescriptionsFieldLabel: 'Show descriptions (Card layout)',
    OpenInNewTabFieldLabel: 'Open links in new tab by default',
    LayoutCardLabel: 'Card Grid',
    LayoutCompactLabel: 'Compact List',
    LayoutTileLabel: 'Tiles',
    NoListSelectedMessage: 'Configure Navigation Tabs',
    NoListSelectedDescription: 'Select a list in the web part properties to display navigation links.',
    LoadingMessage: 'Loading navigation links...',
    ErrorMessage: 'An error occurred while loading navigation links.',
    EmptyMessage: 'No active navigation links found in the selected list.',
    EditListLinkText: 'Edit list items',
    ListGeneratorGroupName: 'List Generator',
    NewListNameFieldLabel: 'New list name',
    NewListNameDescription: 'Creates a new SharePoint list with all the required columns for Navigation Tabs.',
    NewListNamePlaceholder: 'e.g. Navigation Links',
    CreateListButtonLabel: 'Create List',
    CreatingListButtonLabel: 'Creating...',
    TabOrderGroupName: 'Tab Order',
    TabOrderFieldLabel: 'Use arrows to reorder tabs',
  };
});
